Feature/annie html exercise2
Annie2106/html-tutorial pull request #2
Opened 2020-04-26 01:13 UTC by Annie2106

Hello! I woul like to share with you all my exercise. Thank you

2020-04-29 02:22 UTC, pushdev-code commented on 1-the-basics/AnnieBasicExc1.html
> +    </body>
This file was the same of the first Pull Request. Please make sure to create the new branch from the *master* branch. In this case, you are adding the files of the first exercise because probably you created the *feature/Annie-html-exercise2* branch from the of the first exercise branch.

2020-04-29 02:23 UTC, pushdev-code commented on 3-semantic-html/AnnieSemanticEx2.html
> +        <h2></h2>
This tag is empty

2020-04-29 02:24 UTC, juancho11gm commented on 3-semantic-html/AnnieSemanticEx2.html
> +        <h2></h2>
the `<h2>`

2020-04-29 02:25 UTC, juancho11gm commented on 3-semantic-html/AnnieSemanticEx2.html
> +        <p>So this relationship began by mutual benefits cats could eat and farmers kept free from rats.</p>
Maybe, you can have some of these lines in the same `<p>`.

2020-04-29 02:25 UTC, juancho11gm commented on 3-semantic-html/AnnieSemanticEx2.html
> +    <t3>My own experience with cats</t3>
```suggestion
    <h3>My own experience with cats</h3>
```

2020-04-29 02:26 UTC, juancho11gm commented on 3-semantic-html/AnnieSemanticEx2.html
> +        <br>
avoid this `<br>`

2020-04-29 02:26 UTC, juancho11gm commented on 3-semantic-html/AnnieSemanticEx2.html
> +        <img heiht = " 400" width = "400" src ="C:\Users\Bivi Anne\Documents\push-dev\html-tutorial\3-semantic-html/1.jpg  " alt = "Tut"/>
```suggestion
        <img hegiht=" 400" width="400" src ="/1.jpg  " alt = "Tut"/>
```

2020-04-29 02:28 UTC, juancho11gm commented on 3-semantic-html/AnnieSemanticEx2.html
> +        <img heiht = " 400" width = "400" src ="C:\Users\Bivi Anne\Documents\push-dev\html-tutorial\3-semantic-html/1.jpg  " alt = "Tut"/>
In the `src` attribute you can put the relative path of the file. In the `alt` attribute put a specific description of the image.

2020-04-29 02:29 UTC, juancho11gm commented on 3-semantic-html/AnnieSemanticEx2.html
> +        <br>
avoid `<br>`

2020-04-29 02:30 UTC, juancho11gm commented on 3-semantic-html/AnnieSemanticEx2.html
> +        <a href="vivi.c11@hotmail.com">e-amil</a>
```suggestion
        <a href = "mailto: vivi.c11@hotmail.com">Send Email</a>
```

2020-04-29 02:31 UTC, juancho11gm requested changes
Good job, please see the comments and send the changes.

2020-05-05 13:08 UTC, Annie2106 commented
I created a new branch, because I made a mistake using the same branch of the first one

2020-05-05 13:08 UTC, closed without merging