Feature/annie html exercise3
Annie2106/html-tutorial pull request #3
Opened 2020-04-26 01:23 UTC by Annie2106

Hello, I want to share with you the exercise 3. Thanks

2020-04-29 02:13 UTC, pushdev-code requested changes
Please double check the `for` attribute values in your labels, They should match their corresponding input id. 
Use input ids without spaces.
Please include the basic structure for an HTML document.

2020-04-29 02:13 UTC, pushdev-code commented on 4-forms-validations/AnnieFormEx3.html
> +<p>Welcome to PintaYa Form
you're missing the basic structure of the html document. Don't forget to include `<html>, <head>, <title>, <body>`

2020-04-29 02:13 UTC, pushdev-code commented on 4-forms-validations/AnnieFormEx3.html
> +    <img heiht = " 100" width = "100" src ="C:\Users\Bivi Anne\Documents\push-dev\html-tutorial\4-forms-validations/pinta.jpg  " alt = "PintaYa"/>
You don't need spaces in between attributes and values. For the src, you can do:
```suggestion
    <img height="100" width="100" src="pinta.jpg" alt="PintaYa"/>
```

2020-04-29 02:13 UTC, pushdev-code commented on 4-forms-validations/AnnieFormEx3.html
> +    <label for="personal information">Personal Information</label>
These should not be a label but a heading or a paragraph.

2020-04-29 02:13 UTC, pushdev-code commented on 4-forms-validations/AnnieFormEx3.html
> +    <input type= "text" id= "name" name= "user_name" >
```suggestion
    <label for="name">First Name</label>
    <input type= "text" id= "name" name= "user_name" >
```
The attribute for should match the id of the input it is related to.

2020-04-29 02:13 UTC, pushdev-code commented on 4-forms-validations/AnnieFormEx3.html
> +    <input type="number" id= "celular number" name= "user_number">
you're missing the required attribute.

```suggestion
    <input type="number" id= "celular number" name= "user_number" required>
```

2020-04-29 02:13 UTC, pushdev-code commented on 4-forms-validations/AnnieFormEx3.html
> +    <input type="email" name="e-mail" required="required" oninvalid="setCustomValidity('share us your email')" oninput="setCustomValidity('')">
this is great, you put your custom message!

2020-04-29 02:13 UTC, pushdev-code commented on 4-forms-validations/AnnieFormEx3.html
> +        </datalist>
nice to see you used a `<datalist>`

2020-04-29 02:13 UTC, pushdev-code commented on 4-forms-validations/AnnieFormEx3.html
> +
these spaces can be removed.

2020-04-29 02:13 UTC, pushdev-code commented on 4-forms-validations/AnnieFormEx3.html
> +    <input type="submit" value="Submit">
```suggestion
    <input value="Submit">   
```

2020-05-09 20:53 UTC, Annie2106 commented
Sorry! I made a huge mistake, that's why I have a new one.

2020-05-09 20:53 UTC, closed without merging